-- Sistem Nilai MDT: centralized app state table
create table if not exists app_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table app_state enable row level security;

drop policy if exists "app_state_select_anon" on app_state;
create policy "app_state_select_anon" on app_state for select using (true);

drop policy if exists "app_state_insert_anon" on app_state;
create policy "app_state_insert_anon" on app_state for insert with check (true);

drop policy if exists "app_state_update_anon" on app_state;
create policy "app_state_update_anon" on app_state for update using (true) with check (true);

insert into app_state (key, value) values
  ('CL', '{"aw1a":{"name":"Awwaliyah I A","sh":"AW I A","wali":"Aan Widianto, M.Pd","mapel":["Praktek Aqoid","Tauhid","Fiqih Praktik","Fiqih","Akhlaq","Imla''","Tarikh"]},"aw1b":{"name":"Awwaliyah I B","sh":"AW I B","wali":"Idris, S.Pd","mapel":["Praktek Aqoid","Tauhid","Fiqih Praktik","Fiqih","Akhlaq","Imla''","Tarikh"]},"aw2a":{"name":"Awwaliyah II A","sh":"AW II A","wali":"Muhammad Danil","mapel":["Tauhid","Fiqih","Fiqih (Lisan)","Akhlaq","Nahwu","Shorof (Tulis)","Shorof (Lisan)","Aswaja"]},"aw2b":{"name":"Awwaliyah II B","sh":"AW II B","wali":"Adam Muhammad Rois","mapel":["Tauhid","Fiqih","Fiqih (Lisan)","Akhlaq","Nahwu","Shorof (Tulis)","Shorof (Lisan)","Aswaja"]},"aw3a":{"name":"Awwaliyah III A","sh":"AW III A","wali":"M. Syariful Umam, S.H","mapel":["Tauhid","Fiqih Praktik","Fiqih","Akhlaq","Nahwu","Shorof","Aswaja","I''lal","BMK"]},"ws1":{"name":"Wustho I","sh":"WS I","wali":"Faiq Al Himam, S.H","mapel":["Tauhid","Fiqih Praktik","Fiqih","Akhlaq","Nahwu","Shorof","Ushul Fiqh","Tarikh","Tafsir","BMK","Hadits"]},"ws2":{"name":"Wustho II","sh":"WS II","wali":"M. Zayyan Muzadi, S.Ag","mapel":["Tauhid","Fiqih Praktik","Fiqih","Akhlaq","Nahwu","Shorof","Ushul Fiqh","Tarikh","Tafsir","BMK","Hadits"]}}'::jsonb),
  ('ST', '{"aw1a":["Achmad Zahran Shobir","Aimar Ainul Hisyam","Alif Mulia Ramadani","Alvaro Hikamul Anam","Chiko Villa Putra","Dafa Adi Putra","Fahmy Abrory","Lucky Ali","Moh. Fatih Nasrullah Fiddaroin","Mohammad Hidayatul Vikri","M. Rafka Pratama D. A. F.","Mohammad Zafran Sayyid A.","Muhammad Arfin Maulana","Muhammad Azril Maulana F.","Muhammad Fadil","Muhammad Falih Sabilil Faradis","Muhammad Febrian Agustino","Muhammad Hirzul Azali B. P.","Nur Rizki Ramadani","Rohikim Mahtum","Ubaidillah Arroyan","Wahyu Ubaidillah","Zayan Nizar Irfani","Zulfikar Nabil Fahmi","Rijal Anawar Sadad","A. Farel","M. Bagus Mugarrabin","M. Daffa Jadid"],"aw1b":["A. Saputra","Ahmad Aerlangga Eka Bimantara","Ahmad Irfan Ubaidillah","Aliyul Azmi","Bashelo Ghulam Abinaya","Fikri Ilhamul Bari","Julian Ramadhan","Labib Fanani","M. Fahmi Maulana","Mohammad Abdul Razak","Mohammad Aufar Ristian","Mohammad Khairul Ibad","Muhammad Al Fatih Al Fazio G.","Muhammad Alfian Fauzi","Muhammad Nazriel Akbar F.","Muhammad Nurul Furqon H.","Muhammad Rofiqi","Muhammad Rohid Mustofa R.","Muhammad Rois Al Hanif","Muhammad Sabiq Al-Khair","Muhammad Yusuf Al-Arda Bili","Mu''id Zawir","Rafa Hafidz Ghaisan","Rafqa Tsabit Rabbani","Raja Devan Putra Fauzi","Rakan Ikhwan Azam","Syafiq Abil Qasim","Muhammad Virgizt Erlangga","William Felix Satria Tama"],"aw2a":["Ahmad Athif Maulidi","Candra Hakim Alamsyah P.","Fathur Riziq Ubaidillah","Hazel Alvaro Zhafran","Ifat Maulana Firli","M. Ashil Ghozali","M. Hisyam Ali B.","M. Irfan Maulana","M. Nazril Ilham","Moch. Febri Zainurrohman","Moch. Fida'' Gifar Ali","Muhammad Nizam Fiyhi A.","Saif Ahkam Aidil"],"aw2b":["Ahmad Suhaeri","Bambang Pamungkas","Bayu Bagus Sujiwo","Dliya''ul Haq","Egi Melgiansyah","Farel Asis Pratama","Irsyad Tamhidy","M. Breyen Adi Saputra","M. Fajril Falah","M. Gufron Ainurrofi R","M. Nur Soba","M. Sadid Hilmy Fairuz","Mochammad Alfan Sholihin A"],"aw3a":["A. Fathan","Abdulqodir Jaelani","Ahmad Fauzi Ibad F.","Fazlurrohman Ar-Ru''yan","M. Alfan Hidayat","M. Alga Nuril Jadid","M. Fadhal Ramadhani","M. Faris Zaki","M. Gahzy Firjatullah","M. Nur Syai''d","M. Rosyidil Quran","M. Wahyu Hakiki","M. Zaki Hilmi","Mochammad Rafi Alfatah","Muhammad Irvaani","Nazril Fahri Ayubi D","Sultan Muaffaq Takazza R","Wildan Azka Danish","Miqdad Izuul M."],"ws1":["A. Fajar Saputra","A. Fathi Mubarak","A. Sahril Habibi","Difan Hakil Fikron","M. Alif Esfandiar","M. Fahril Umam","M. Najiburrahman","M. Ubaidillah Ar-Roziqin","Mahtum Hardiansyah","Mandala Ridho Ramadan","Moh. Sofyan Pratama","Muhammad Farel Iskandar","Rozinul Haq","Zakil Widad","Zizky Fairous Syaif"],"ws2":["Akmal Abdillah Amir","Bilbar Nafuz","M. Azif Ridho","M. Bayu Ramdani","M. Sulthan Malik Ibrahim","Moh. Abdurrohman","Nadhif Fahmil Faqih B.K"]}'::jsonb),
  ('GM', '{"guru_tauhid":[{"k":"aw1a","m":["Tauhid"]},{"k":"aw1b","m":["Tauhid"]},{"k":"aw2a","m":["Tauhid"]},{"k":"aw2b","m":["Tauhid"]},{"k":"aw3a","m":["Tauhid"]},{"k":"ws1","m":["Tauhid"]},{"k":"ws2","m":["Tauhid"]}],"guru_fiqih":[{"k":"aw1a","m":["Fiqih Praktik","Fiqih"]},{"k":"aw1b","m":["Fiqih Praktik","Fiqih"]},{"k":"aw2a","m":["Fiqih","Fiqih (Lisan)"]},{"k":"aw2b","m":["Fiqih","Fiqih (Lisan)"]},{"k":"aw3a","m":["Fiqih Praktik","Fiqih"]},{"k":"ws1","m":["Fiqih Praktik","Fiqih"]},{"k":"ws2","m":["Fiqih Praktik","Fiqih"]}],"guru_akhlaq":[{"k":"aw1a","m":["Akhlaq"]},{"k":"aw1b","m":["Akhlaq"]},{"k":"aw2a","m":["Akhlaq"]},{"k":"aw2b","m":["Akhlaq"]},{"k":"aw3a","m":["Akhlaq"]},{"k":"ws1","m":["Akhlaq"]},{"k":"ws2","m":["Akhlaq"]}],"guru_aqoid":[{"k":"aw1a","m":["Praktek Aqoid"]},{"k":"aw1b","m":["Praktek Aqoid"]}],"guru_imla":[{"k":"aw1a","m":["Imla''"]},{"k":"aw1b","m":["Imla''"]}],"guru_tarikh":[{"k":"aw1a","m":["Tarikh"]},{"k":"aw1b","m":["Tarikh"]},{"k":"ws1","m":["Tarikh"]},{"k":"ws2","m":["Tarikh"]}],"guru_nahwu":[{"k":"aw2a","m":["Nahwu"]},{"k":"aw2b","m":["Nahwu"]},{"k":"aw3a","m":["Nahwu"]},{"k":"ws1","m":["Nahwu"]},{"k":"ws2","m":["Nahwu"]}],"guru_shorof":[{"k":"aw2a","m":["Shorof (Tulis)","Shorof (Lisan)"]},{"k":"aw2b","m":["Shorof (Tulis)","Shorof (Lisan)"]},{"k":"aw3a","m":["Shorof"]},{"k":"ws1","m":["Shorof"]},{"k":"ws2","m":["Shorof"]}],"guru_ushul":[{"k":"ws1","m":["Ushul Fiqh"]},{"k":"ws2","m":["Ushul Fiqh"]}],"guru_tafsir":[{"k":"ws1","m":["Tafsir"]},{"k":"ws2","m":["Tafsir"]}],"guru_bmk":[{"k":"aw3a","m":["BMK"]},{"k":"ws1","m":["BMK"]},{"k":"ws2","m":["BMK"]}],"guru_hadits":[{"k":"ws1","m":["Hadits"]},{"k":"ws2","m":["Hadits"]}],"guru_aswaja":[{"k":"aw2a","m":["Aswaja"]},{"k":"aw2b","m":["Aswaja"]},{"k":"aw3a","m":["Aswaja"]}],"guru_ilal":[{"k":"aw3a","m":["I''lal"]}]}'::jsonb),
  ('ACCS', '[{"u":"admin","p":"admin123","role":"admin","name":"Administrator"},{"u":"wali_aw1a","p":"wali123","role":"wk","name":"Aan Widianto, M.Pd","kelas":"aw1a"},{"u":"wali_aw1b","p":"wali123","role":"wk","name":"Idris, S.Pd","kelas":"aw1b"},{"u":"wali_aw2a","p":"wali123","role":"wk","name":"Muhammad Danil","kelas":"aw2a"},{"u":"wali_aw2b","p":"wali123","role":"wk","name":"Adam Muhammad Rois","kelas":"aw2b"},{"u":"wali_aw3a","p":"wali123","role":"wk","name":"M. Syariful Umam, S.H","kelas":"aw3a"},{"u":"wali_ws1","p":"wali123","role":"wk","name":"Faiq Al Himam, S.H","kelas":"ws1"},{"u":"wali_ws2","p":"wali123","role":"wk","name":"M. Zayyan Muzadi, S.Ag","kelas":"ws2"},{"u":"guru_tauhid","p":"guru123","role":"guru","name":"Guru Tauhid"},{"u":"guru_fiqih","p":"guru123","role":"guru","name":"Guru Fiqih"},{"u":"guru_akhlaq","p":"guru123","role":"guru","name":"Guru Akhlaq"},{"u":"guru_aqoid","p":"guru123","role":"guru","name":"Guru Praktek Aqoid"},{"u":"guru_imla","p":"guru123","role":"guru","name":"Guru Imla''"},{"u":"guru_tarikh","p":"guru123","role":"guru","name":"Guru Tarikh"},{"u":"guru_nahwu","p":"guru123","role":"guru","name":"Guru Nahwu"},{"u":"guru_shorof","p":"guru123","role":"guru","name":"Guru Shorof"},{"u":"guru_ushul","p":"guru123","role":"guru","name":"Guru Ushul Fiqh"},{"u":"guru_tafsir","p":"guru123","role":"guru","name":"Guru Tafsir"},{"u":"guru_bmk","p":"guru123","role":"guru","name":"Guru BMK"},{"u":"guru_hadits","p":"guru123","role":"guru","name":"Guru Hadits"},{"u":"guru_aswaja","p":"guru123","role":"guru","name":"Guru Aswaja"},{"u":"guru_ilal","p":"guru123","role":"guru","name":"Guru I''lal"}]'::jsonb),
  ('allG', '{}'::jsonb),
  ('allKep', '{}'::jsonb)
on conflict (key) do nothing;

alter publication supabase_realtime add table app_state;
